App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Shop/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(
        max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]

App_Shop/views.py
from django.shortcuts import render

# Import views
from django.views.generic import ListView, DetailView

# Models
from App_Shop.models import Product

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class Home(ListView):
    paginate_by = 8
    model = Product
    template_name = 'App_Shop/home.html'


class ProductDetail(DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'

# class ProductDetail(LoginRequiredMixin, DetailView):
#     model = Product
#     template_name = 'App_Shop/product_detail.html'

templates/App_Shop/home.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<!-- Banner Section -->
<div class="banner">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/banner_1.jpg' %}" class="d-block w-100 img-fluid" alt="Banner">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/banner_2.png' %}" class="d-block w-100 img-fluid" alt="Banner">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/banner_3.jpg' %}" class="d-block w-100 img-fluid" alt="Banner">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<!-- END of Banner -->

<!-- Products Category -->
<div class="products-section m-4 p-2">
    <div class="container">
        <div class="row m-auto">
            <div class="col text-center">
                <h2 class="">Featured Products</h2>
            </div>
        </div>
    </div>
</div>
</div>

<!-- Products Cards -->
<div class="container my-5">
    <div class="row">
        {% for product in object_list %}
        <div class="col-md-6 col-sm-12 col-lg-3">
            <figure class="card card-product">
                <div class="img-wrap">
                    <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
                </div>
                <figcaption class="info-wrap">
                    <h6 class="title"><a href="{% url 'App_Shop:product_detail' pk=product.pk %}">{{product.name}}</a>
                    </h6>
                    <div class="action-wrap">
                        <div class="price-wrap h5">
                            <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
                            <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
                        </div>
                    </div>
                </figcaption>
            </figure>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Pagination -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            {% if page_obj.has_previous %}
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                aria-disabled="true">Previous</a>
            {% endif %}
        </li>

        <li class="page-item">
            <a class="page-link" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}</a>
        </li>

        <li class="page-item"></li>
        {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
        </li>
    </ul>
</nav>

<!-- This is where the footer begins -->
<style>
    footer {
        padding: 15px 23px;
        color: #111;
        text-align: center;
    }
</style>

<footer>
    <span>Developed by <a href="https://iamshantoo.github.io">Md. Abul Hasan</a> | <span
            class="far fa-copyright"></span> 2021
        All rights reserved.</span>
</footer>

{% endblock body_block%}

templates/App_Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
                        </div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>
                            <p>{{object.detail_text|linebreaks}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'App_Order:add' pk=object.pk %}"
                        class="btn btn-lg btn-outline-primary text-uppercase">
                        <i class="fas fa-shopping-cart"></i> Add
                        to Cart</a>
                </article>
            </aside>
        </div>
    </div>
</div>
{% endblock %}