App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>/', views.add_to_cart, name="add"),
    path('remove/<pk>/', views.remove_from_cart, name="remove"),
    path('cart/', views.cart_view, name="cart"),
    path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

App_Payment/urls.py
from django.urls import path
from App_Payment import views

app_name = "App_Payment"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),
]

App_Shop/urls.py
from django.urls import path
from App_Shop import views

app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
]

My_Ecom_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('account/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('payment/', include('App_Payment.urls'))

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title_block %} E-Shop | Computers {% endblock %}</title>

    <style>
        .card {
            height: 350px;
        }

        .card-product:after {
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }

        .card-product .price-new,
        .card-product .price {
            margin-right: 5px;
        }

        .card-product .price-old {
            color: #999;
        }

        .card-product .img-wrap {
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }

        .card-product .img-wrap img {
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }

        .card-product .info-wrap {
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .action-wrap {
            padding-top: 4px;
            margin-top: 4px;
        }

        .card-product .bottom-wrap {
            padding: 15px;
            border-top: 1px solid #eee;
        }

        .card-product .title {
            margin-top: 0px;
        }
    </style>

</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
            {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags}}{% endif %}" role="alert">
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="close"><span
                        aria-hidden="true">&times;</span></button>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% block body_block %} {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
{% load cart_tag %}
<div class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'App_Shop:home' %}">E-Shop | Computers</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <form class="form-inline ml-auto">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </form>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Components</a>
                        <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
                            <a class="dropdown-item" href="/">Processor</a>
                            <a class="dropdown-item" href="/">Graphics Card</a>
                            <a class="dropdown-item" href="/">Monitor</a>
                            <a class="dropdown-item" href="/">RAM</a>
                            <a class="dropdown-item" href="/">Motherboard</a>
                            <a class="dropdown-item" href="/">Casing</a>
                            <a class="dropdown-item" href="/">Keyboard</a>
                            <a class="dropdown-item" href="/">Mouse</a>
                            <a class="dropdown-item" href="/">SSD</a>
                            <a class="dropdown-item" href="/">HDD</a>
                            <a class="dropdown-item" href="/">Power Supply</a>
                            <a class="dropdown-item" href="/">CPU Cooler</a>
                            <a class="dropdown-item" href="/">UPS</a>
                            <a class="dropdown-item" href="/">Headset</a>
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'App_Order:cart' %}" class="nav-link">
                            <i class="fa fa-shopping-cart"></i> Cart
                            <span class="badge badge-light">{{ request.user | cart_total }}</span>
                        </a>
                    </li>
                    <li class="nav-item">

                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
                                class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
                        <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
                            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'App_Payment:orders' %}">Orders</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'App_Login:login' %}" class="btn btn-primary btn-sm px-3 mx-3">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'App_Login:signup' %}" class="btn btn-success btn-sm">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>